### ISSUE TITLE
IOB gets cut off in portrait view on 4" screen

### ISSUE THREAD

**Issue by sarahspins** [loudnate/LoopKit#43]
Using iPhone SE

Portrait view:
![img_0515](https://cloud.githubusercontent.com/assets/16582717/16997047/65cf9f76-4e79-11e6-8e7b-e85169d7d166.png)

Landscape view:
![img_0516](https://cloud.githubusercontent.com/assets/16582717/16997120/b55efe4c-4e79-11e6-9cd0-1ebdff5b2a55.png)

I've noticed it happening with pretty much every time the IOB has two decimal places that isn't something like x.1x or x.x1

**Comment by sarahspins** [comment]
Still doing it with the IOB.. I realized I put the wrong screen size when I created the issue, I'm not sure if that makes a difference.. but I added the phone model above just for clarity 👍 

![img_0533](https://cloud.githubusercontent.com/assets/16582717/17012978/0ab545a6-4ee1-11e6-8c61-307230ffec0a.png)

**Comment by loudnate** [comment]
Sorry to ask, but there might be some confusion about whether this change was  included in that release tag of Loop last night. It wasn't; it will be included in a future release. 

Alternatively, you could have built Loop against LoopKit's Dev branch using Carthage? If so I apologize and I'll try again to fix this before closing the ticket.
