### ISSUE TITLE
Store RileyLink Device ID in PumpEvent object

### ISSUE THREAD

**Issue by loudnate** [loudnate/LoopKit#48]
Request from @ps2. What should be stored? Just the RileyLink's name?

**Comment by ps2** [comment]
I came around in our discussion.  I think pumpID is the only thing required here.  Is that already covered then as far as this ticket goes. There is still work in NightscoutUploadKit, to add pumpID.

**Comment by loudnate** [comment]
I see pumpID in the device status uploading PR. So what should we use for the device ID? Or is that something you plan to remove?

**Comment by ps2** [comment]
For pump events / treatments, we don't need a 'device ID'.  But as we discussed, tracking the pump that an event came from could be a very useful thing.  I'd like to add this, even though it doesn't exist now.

The pumpID in PumpStatus struct is to know which pump the battery/res/etc was reported for, when doing devicestatus uploads.  This is not currently tracked either, but I'd like to add it.

The device id for devicestatus entries is discussed here: https://github.com/loudnate/Loop/issues/98

**Comment by loudnate** [comment]
There was some confusion here on my part; it sounds like we don't need to store deviceID for nightscout.
