### ISSUE TITLE
Store trend in GlucoseStore

### ISSUE THREAD

**Issue by ps2** [loudnate/LoopKit#59]
Trend is displayed in Loop in the GlucoseHUD.  We can't display trend data from share, as those values go through GlucoseStore.

**Comment by loudnate** [comment]
Share glucose never returns trend data, actually.

**Comment by ps2** [comment]
Hmm, NS is getting trend data from Share.

**Comment by loudnate** [comment]
Must be a bug in the Share downloader, then. Why do we need to store trend if not for NS?

**Comment by ps2** [comment]
Loop glucoseHUD shows it (gets trend directly from SensorDisplayable, but it's missing if getting data

**Comment by loudnate** [comment]
Right so no need to store it in HealthKit just to display the latest value. Can you open a bug in the share downloader?

**Comment by ps2** [comment]
Ok, sounds good.
