### ISSUE TITLE
The last temp basal of 0 duration isn't removed 

### ISSUE THREAD

**Issue by loudnate** [loudnate/LoopKit#68]
This is @channemann's issue, which wasn't fixed.

**Comment by channemann** [comment]
![image](https://cloud.githubusercontent.com/assets/5387400/18226325/4d27517e-71bc-11e6-9dc8-a2b398fb2241.png)
![image](https://cloud.githubusercontent.com/assets/5387400/18226328/53dba808-71bc-11e6-8571-db55211a68c5.png)
![image](https://cloud.githubusercontent.com/assets/5387400/18226329/59434328-71bc-11e6-8d1d-3151bb39114d.png)
![image](https://cloud.githubusercontent.com/assets/5387400/18226331/623f3112-71bc-11e6-9b8a-f857338eb91b.png)
![image](https://cloud.githubusercontent.com/assets/5387400/18226332/671709f8-71bc-11e6-885b-4446e33f8b77.png)
